name: animation
description: "Weather App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.8.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  flutter_spinkit: ^5.2.0
  geolocator: ^11.0.0  # For live location

flutter:
  uses-material-design: true